In [2]:
import numpy as np
import pandas as pd

In [9]:
beta_data = pd.read_csv('./probs/beta_probs.csv',header=None).to_numpy()
delta_data = pd.read_csv('./probs/delta_probs.csv',header=None).to_numpy()
gamma_data = pd.read_csv('./probs/gamma_probs.csv',header=None).to_numpy()
lambda_data = pd.read_csv('./probs/lambda_probs.csv',header=None).to_numpy()

In [10]:
for i in range(3822):
    beta_line, delta_line, gamma_line, lambda_line = beta_data[:,i], delta_data[:,i], gamma_data[:,i], lambda_data[:,i]
    if (beta_line==delta_line).all() and (beta_line==gamma_line).all() and (beta_line==lambda_line).all():
        continue
    print(i+1)
    print(beta_line)
    print(delta_line)
    print(gamma_line)
    print(lambda_line)
    print()

6
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[7.20201656e-04 0.00000000e+00 0.00000000e+00 9.99279798e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

11
[0.    0.975 0.025 0.    0.   ]
[0. 1. 0. 0. 0.]
[1.80050414e-04 9.99819950e-01 0.00000000e+00 0.00000000e+00
 0.00000000e+00]
[0. 1. 0. 0. 0.]

12
[0.         0.00555556 0.99444444 0.         0.        ]
[0.         0.00403769 0.99596231 0.         0.        ]
[0.         0.00630176 0.99369824 0.         0.        ]
[0.         0.00597015 0.99402985 0.         0.        ]

14
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 2.69179004e-04 0.00000000e+00
 0.00000000e+00]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

15
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[1.80050414e-04 1.80050414e-04 0.00000000e+00 9.99639899e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

20
[0.99444444 0.         0.         0.00555556 0.        ]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 2.69179004e-04
 0.00000000e+00]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

22
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e

[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99099748e-01
 7.20201656e-04]
[0. 0. 0. 1. 0.]

103
[0. 0. 0. 1. 0.]
[0.00000000e+00 5.38358008e-04 0.00000000e+00 9.99461642e-01
 0.00000000e+00]
[0.00000000e+00 3.60100828e-04 0.00000000e+00 9.98919698e-01
 7.20201656e-04]
[0. 0. 0. 1. 0.]

104
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99279798e-01 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[0. 1. 0. 0. 0.]

105
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99279798e-01
 7.20201656e-04]
[0. 0. 0. 1. 0.]

106
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99279798e-01 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[0. 1. 0. 0. 0.]

107
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99279798e-01 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[0. 1. 0. 0. 0.]

108
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99279798e-01 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[0. 1. 0. 0. 0.]

109
[

[0.         0.00612171 0.99387829 0.         0.        ]
[0.         0.00298507 0.99402985 0.         0.00298507]

210
[0. 1. 0. 0. 0.]
[0.         0.98438762 0.         0.         0.01561238]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

211
[0. 0. 1. 0. 0.]
[0.         0.         0.98438762 0.         0.01561238]
[0.00000000e+00 1.80050414e-04 9.99819950e-01 0.00000000e+00
 0.00000000e+00]
[0.         0.         0.99701493 0.         0.00298507]

212
[0. 1. 0. 0. 0.]
[0.         0.98438762 0.         0.         0.01561238]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

213
[0. 0. 0. 1. 0.]
[0.        0.        0.        0.9846568 0.0153432]
[0. 0. 0. 1. 0.]
[0.00298507 0.         0.         0.99402985 0.00298507]

214
[0. 0. 0. 1. 0.]
[2.69179004e-04 0.00000000e+00 0.00000000e+00 9.83580081e-01
 1.61507402e-02]
[0.00198055 0.         0.         0.99801945 0.        ]
[0.00597015 0.         0.         0.99104478 0.00298507]

215

[0.         0.99729924 0.         0.         0.00270076]
[0. 1. 0. 0. 0.]

275
[0. 1. 0. 0. 0.]
[0.         0.98088829 0.         0.         0.01911171]
[0.         0.99729924 0.         0.         0.00270076]
[0. 1. 0. 0. 0.]

276
[0. 0. 0. 1. 0.]
[0.00000000e+00 2.69179004e-04 0.00000000e+00 9.80349933e-01
 1.93808883e-02]
[0.         0.         0.         0.99729924 0.00270076]
[0. 0. 0. 1. 0.]

277
[0. 0. 1. 0. 0.]
[0.         0.         0.98115747 0.         0.01884253]
[0.         0.         0.99729924 0.         0.00270076]
[0. 0. 1. 0. 0.]

278
[0. 1. 0. 0. 0.]
[0.         0.98088829 0.         0.         0.01911171]
[0.         0.99729924 0.         0.         0.00270076]
[0. 1. 0. 0. 0.]

279
[0. 1. 0. 0. 0.]
[0.         0.98115747 0.         0.         0.01884253]
[0.         0.99729924 0.         0.         0.00270076]
[0. 1. 0. 0. 0.]

280
[0. 0. 1. 0. 0.]
[0.         0.         0.98869448 0.         0.01130552]
[0.         0.         0.99765934 0.         0.00234066]
[0. 

[0. 0. 0. 1. 0.]
[0.         0.         0.         0.96850606 0.03149394]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]

367
[0. 0. 1. 0. 0.]
[0.         0.         0.97039031 0.         0.02960969]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]

368
[0. 1. 0. 0. 0.]
[0.         0.97065949 0.         0.         0.02934051]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

369
[1. 0. 0. 0. 0.]
[9.71197847e-01 0.00000000e+00 2.69179004e-04 0.00000000e+00
 2.85329744e-02]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

370
[0. 0. 1. 0. 0.]
[0.00000000e+00 2.69179004e-04 9.71736205e-01 0.00000000e+00
 2.79946164e-02]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]

371
[0. 1. 0. 0. 0.]
[0.        0.9781965 0.        0.        0.0218035]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

372
[1. 0. 0. 0. 0.]
[0.98008075 0.         0.         0.         0.01991925]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

373
[1. 0. 0. 0. 0.]
[0.98008075 0.         0.         0.         0.01991925]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

374
[0. 1. 0. 0. 0.]
[0.         0.98358008 0.         0.      

[0. 1. 0. 0. 0.]
[0.         0.99811575 0.         0.         0.00188425]
[0.         0.99549874 0.         0.         0.00450126]
[0.         0.99402985 0.         0.         0.00597015]

429
[0. 1. 0. 0. 0.]
[0.         0.99811575 0.         0.         0.00188425]
[0.         0.99549874 0.         0.         0.00450126]
[0.         0.99402985 0.         0.         0.00597015]

430
[1. 0. 0. 0. 0.]
[0.99784657 0.         0.         0.         0.00215343]
[0.99549874 0.         0.         0.         0.00450126]
[0.99402985 0.         0.         0.         0.00597015]

431
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99461642e-01 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[0.00000000e+00 9.99639899e-01 0.00000000e+00 0.00000000e+00
 3.60100828e-04]
[0. 1. 0. 0. 0.]

432
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0.00000000e+00 9.99639899e-01 0.00000000e+00 0.00000000e+00
 3.60100828e-04]
[0. 1. 0. 0. 0.]

433
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0

[1. 0. 0. 0. 0.]
[0.99757739 0.         0.         0.         0.00242261]
[9.96579042e-01 0.00000000e+00 1.80050414e-04 0.00000000e+00
 3.24090745e-03]
[1. 0. 0. 0. 0.]

490
[1. 0. 0. 0. 0.]
[0.99757739 0.         0.         0.         0.00242261]
[0.99675909 0.         0.         0.         0.00324091]
[1. 0. 0. 0. 0.]

491
[0. 1. 0. 0. 0.]
[0.         0.99811575 0.         0.         0.00188425]
[0.         0.99675909 0.         0.         0.00324091]
[0. 1. 0. 0. 0.]

492
[1. 0. 0. 0. 0.]
[0.99838493 0.         0.         0.         0.00161507]
[0.99675909 0.         0.         0.         0.00324091]
[1. 0. 0. 0. 0.]

493
[1. 0. 0. 0. 0.]
[0.99838493 0.         0.         0.         0.00161507]
[0.99693914 0.         0.         0.         0.00306086]
[1. 0. 0. 0. 0.]

494
[0. 1. 0. 0. 0.]
[0.         0.99838493 0.         0.         0.00161507]
[0.         0.99693914 0.         0.         0.00306086]
[0. 1. 0. 0. 0.]

495
[0. 1. 0. 0. 0.]
[0.         0.99838493 0.         0.        

[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99730821e-01
 2.69179004e-04]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99459849e-01
 3.60100828e-04]
[0. 0. 0. 1. 0.]

551
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0.00000000e+00 9.99459849e-01 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[0. 1. 0. 0. 0.]

552
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[9.99279798e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[1. 0. 0. 0. 0.]

553
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[9.99279798e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[1. 0. 0. 0. 0.]

554
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99192463e-01 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.00000000e+00 9.99459849e-01 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[0. 1. 0. 0. 0.]

555
[0. 1. 0. 0. 0.]
[0.00000

615
[1. 0. 0. 0. 0.]
[0.99892328 0.         0.         0.         0.00107672]
[9.99099748e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.00252071e-04]
[1. 0. 0. 0. 0.]

616
[1. 0. 0. 0. 0.]
[0.99892328 0.         0.         0.         0.00107672]
[9.99099748e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.00252071e-04]
[1. 0. 0. 0. 0.]

617
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99892328 0.00107672]
[0.        0.        0.        0.9989197 0.0010803]
[0. 0. 0. 1. 0.]

618
[0. 0. 1. 0. 0.]
[0.         0.         0.99892328 0.         0.00107672]
[0.         0.         0.99873965 0.         0.00126035]
[0. 0. 1. 0. 0.]

619
[1. 0. 0. 0. 0.]
[0.99892328 0.         0.         0.         0.00107672]
[0.99837955 0.         0.         0.         0.00162045]
[1. 0. 0. 0. 0.]

620
[0. 0. 1. 0. 0.]
[0.         0.         0.99892328 0.         0.00107672]
[0.         0.         0.99837955 0.         0.00162045]
[0. 0. 1. 0. 0.]

621
[1. 0. 0. 0. 0.]
[0.99892328 0.         0

[0.         0.         0.         0.99402985 0.00597015]

678
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99811575 0.00188425]
[0.         0.         0.         0.99747929 0.00252071]
[0.         0.         0.         0.99402985 0.00597015]

679
[0. 1. 0. 0. 0.]
[0.         0.99811575 0.         0.         0.00188425]
[0.         0.99747929 0.         0.         0.00252071]
[0.         0.99402985 0.         0.         0.00597015]

680
[1. 0. 0. 0. 0.]
[0.99784657 0.         0.         0.         0.00215343]
[0.9978394 0.        0.        0.        0.0021606]
[0.99402985 0.         0.         0.         0.00597015]

681
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99784657 0.00215343]
[0.        0.        0.        0.9978394 0.0021606]
[0.         0.         0.         0.99402985 0.00597015]

682
[1. 0. 0. 0. 0.]
[0.99784657 0.         0.         0.         0.00215343]
[0.9978394 0.        0.        0.        0.0021606]
[0.99402985 0.         0.         0.         0.005

[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99192463e-01 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0.         0.02686567 0.         0.         0.97313433]

742
[1. 0. 0. 0. 0.]
[9.99192463e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0.02686567 0.         0.         0.         0.97313433]

743
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99192463e-01 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0.         0.02686567 0.         0.         0.97313433]

744
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99192463e-01 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0.         0.02686567 0.         0.         0.97313433]

745
[0. 1. 0. 0. 0.]
[0.         0.99892328 0.         0.       

[0.         0.99837955 0.         0.         0.00162045]
[0.         0.98208955 0.         0.         0.01791045]

783
[0.         0.         0.         0.84722222 0.15277778]
[0.         0.         0.         0.98950202 0.01049798]
[0.        0.        0.        0.9978394 0.0021606]
[0.         0.         0.         0.98208955 0.01791045]

784
[0.         0.         0.81388889 0.         0.18611111]
[0.         0.         0.98896366 0.         0.01103634]
[0.         0.         0.99711919 0.         0.00288081]
[0.         0.         0.98507463 0.         0.01492537]

785
[0.         0.80277778 0.         0.         0.19722222]
[0.        0.9884253 0.        0.        0.0115747]
[0.         0.99729924 0.         0.         0.00270076]
[0.         0.98507463 0.         0.         0.01492537]

786
[0.         0.         0.         0.80277778 0.19722222]
[0.         0.         0.         0.98815612 0.01184388]
[0.         0.         0.         0.99693914 0.00306086]
[0.         0.0029850

[0.         0.98761777 0.         0.         0.01238223]
[0.         0.99621894 0.         0.         0.00378106]
[0.         0.99104478 0.         0.         0.00895522]

824
[0.         0.81388889 0.         0.         0.18611111]
[0.         0.98788694 0.         0.         0.01211306]
[0.         0.99657904 0.         0.         0.00342096]
[0.         0.99402985 0.         0.         0.00597015]

825
[0.         0.         0.81666667 0.         0.18333333]
[0.         0.         0.98707941 0.         0.01292059]
[0.00000000e+00 9.00252071e-04 9.95498740e-01 0.00000000e+00
 3.60100828e-03]
[0.         0.         0.99402985 0.         0.00597015]

826
[0.         0.83333333 0.         0.         0.16666667]
[0.         0.98707941 0.         0.         0.01292059]
[0.         0.99657904 0.         0.         0.00342096]
[0.         0.99402985 0.         0.         0.00597015]

827
[0.83611111 0.         0.         0.         0.16388889]
[0.98761777 0.         0.         0.         0.

[2.69179004e-04 0.00000000e+00 0.00000000e+00 9.86541050e-01
 1.31897712e-02]
[0.         0.         0.         0.99585884 0.00414116]
[0.         0.         0.02089552 0.9761194  0.00298507]

865
[0.         0.92777778 0.         0.         0.07222222]
[0.         0.98681023 0.         0.         0.01318977]
[0.         0.99585884 0.         0.         0.00414116]
[0.         0.99701493 0.         0.         0.00298507]

866
[0.92222222 0.         0.         0.         0.07777778]
[0.98654105 0.         0.         0.         0.01345895]
[0.99585884 0.         0.         0.         0.00414116]
[0.99402985 0.         0.         0.         0.00597015]

867
[0.         0.         0.         0.92222222 0.07777778]
[0.         0.         0.         0.98519515 0.01480485]
[0.         0.         0.         0.99567879 0.00432121]
[0.         0.         0.         0.99104478 0.00895522]

868
[0.92222222 0.         0.         0.         0.07777778]
[0.98573351 0.         0.         0.         0.

[0.         0.97981157 0.         0.         0.02018843]
[0.         0.99369824 0.         0.         0.00630176]
[0.         0.98507463 0.         0.         0.01492537]

908
[0.         0.         0.         0.88055556 0.11944444]
[0.         0.         0.         0.98008075 0.01991925]
[0.00000000e+00 7.20201656e-04 0.00000000e+00 9.93158084e-01
 6.12171408e-03]
[0.         0.         0.         0.97910448 0.02089552]

909
[0.88888889 0.         0.         0.         0.11111111]
[0.98411844 0.         0.         0.         0.01588156]
[0.99459849 0.         0.         0.         0.00540151]
[0.98507463 0.         0.         0.         0.01492537]

910
[0.89166667 0.         0.         0.         0.10833333]
[0.98734859 0.         0.         0.         0.01265141]
[0.99513864 0.         0.         0.         0.00486136]
[0.9880597 0.        0.        0.        0.0119403]

911
[0.89444444 0.         0.         0.         0.10555556]
[0.98950202 0.         0.         0.         0.01049

[0.        0.9761194 0.        0.        0.0238806]

948
[0.925 0.    0.    0.    0.075]
[0.98815612 0.         0.         0.         0.01184388]
[0.99675909 0.         0.         0.         0.00324091]
[0.9761194 0.        0.        0.        0.0238806]

949
[0.92222222 0.         0.         0.         0.07777778]
[0.98707941 0.         0.         0.         0.01292059]
[0.99675909 0.         0.         0.         0.00324091]
[0.9761194 0.        0.        0.        0.0238806]

950
[0.         0.         0.92222222 0.         0.07777778]
[0.         0.         0.98654105 0.         0.01345895]
[0.00000000e+00 1.80050414e-04 9.96218941e-01 0.00000000e+00
 3.60100828e-03]
[0.         0.         0.97910448 0.         0.02089552]

951
[0.         0.91111111 0.         0.         0.08888889]
[0.         0.98492598 0.         0.         0.01507402]
[0.         0.99585884 0.         0.         0.00414116]
[0.         0.97910448 0.         0.         0.02089552]

952
[0.         0.91111111 0.

[0. 0. 1. 0. 0.]
[0.00000000e+00 1.80050414e-04 9.99639899e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

989
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

990
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

991
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

992
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

993
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

994
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

995
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00

 1.80050414e-04]
[0. 1. 0. 0. 0.]

1053
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

1054
[0. 0. 1. 0. 0.]
[0.00000000e+00 2.69179004e-04 9.99730821e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]

1056
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

1057
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99701493 0.00298507]

1060
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 5.40151242e-04
 0.00000000e+00]
[1. 0. 0. 0. 0.]

1061
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[1.80050414e-04 3.60100828e-04 9.99459849e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

1064
[0. 0. 0. 1. 0.]
[2.69179004e-04 0.00000000e+00 0.00000000e+00 9.99730821e-01
 0.00000000e+00]
[5.40151242e-04 0.00000000e+00 0.00000000e+00 9.99459849e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

1

 5.40151242e-04]
[1. 0. 0. 0. 0.]

1153
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99730821e-01 0.00000000e+00
 2.69179004e-04]
[0.00000000e+00 1.80050414e-04 9.99279798e-01 0.00000000e+00
 5.40151242e-04]
[0. 0. 1. 0. 0.]

1154
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0.00000000e+00 9.99459849e-01 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[0. 1. 0. 0. 0.]

1155
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1156
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1157
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1.

[1. 0. 0. 0. 0.]
[9.99461642e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1203
[1. 0. 0. 0. 0.]
[9.99461642e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1204
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99461642e-01 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[0.00000000e+00 9.99459849e-01 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[0. 1. 0. 0. 0.]

1205
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99461642e-01 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[0.00000000e+00 9.99279798e-01 1.80050414e-04 0.00000000e+00
 5.40151242e-04]
[0. 1. 0. 0. 0.]

1206
[1. 0. 0. 0. 0.]
[9.99461642e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1207
[0. 0. 0. 1. 0.]
[0.

[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

1327
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.         0.         0.99701493 0.         0.00298507]

1328
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

1329
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0.99701493 0.         0.         0.         0.00298507]

1330
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0.97313433 0.         0.         0.0238806  0.00298507]

1331
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0.         0.         0.         0.99701493 0.00298507]

1332
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99701493 0.00298507]

1333
[0.         0.98888889 0.         0.         0.01111111]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.002

[0. 0. 0. 1. 0.]

1374
[0.         0.99444444 0.         0.         0.00555556]
[0.00000000e+00 9.99192463e-01 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.         0.99837955 0.         0.         0.00162045]
[0. 1. 0. 0. 0.]

1375
[0.         0.         0.99444444 0.         0.00555556]
[0.00000000e+00 0.00000000e+00 9.99192463e-01 0.00000000e+00
 8.07537012e-04]
[0.         0.         0.99837955 0.         0.00162045]
[0. 0. 1. 0. 0.]

1376
[0.         0.99166667 0.         0.         0.00833333]
[0.00000000e+00 9.99192463e-01 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.        0.9981995 0.        0.        0.0018005]
[0. 1. 0. 0. 0.]

1377
[0.98611111 0.         0.         0.         0.01388889]
[9.99192463e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.99801945 0.         0.         0.         0.00198055]
[1. 0. 0. 0. 0.]

1378
[0.98611111 0.         0.         0.         0.01388889]
[9.99192463e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 8.0

[0.         0.         0.         0.99801945 0.00198055]
[0. 0. 0. 1. 0.]

1430
[0.         0.         0.99166667 0.         0.00833333]
[0.00000000e+00 0.00000000e+00 9.99192463e-01 0.00000000e+00
 8.07537012e-04]
[1.80050414e-04 7.20201656e-04 9.97299244e-01 1.80050414e-04
 1.62045373e-03]
[0. 0. 1. 0. 0.]

1431
[0.99166667 0.         0.         0.         0.00833333]
[9.99192463e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[0.9985596 0.        0.        0.        0.0014404]
[1. 0. 0. 0. 0.]

1432
[0.         0.         0.99722222 0.         0.00277778]
[9.97846568e-01 0.00000000e+00 1.34589502e-03 0.00000000e+00
 8.07537012e-04]
[3.60100828e-04 1.80050414e-04 9.98019445e-01 0.00000000e+00
 1.44040331e-03]
[0. 0. 1. 0. 0.]

1433
[1. 0. 0. 0. 0.]
[9.99461642e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[0.99837955 0.         0.         0.         0.00162045]
[1. 0. 0. 0. 0.]

1434
[0.         0.         0.99444444 0.         0.00555556]
[0.000

 5.38358008e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1476
[0.         0.         0.99444444 0.         0.00555556]
[0.00000000e+00 0.00000000e+00 9.99461642e-01 0.00000000e+00
 5.38358008e-04]
[0.00000000e+00 0.00000000e+00 9.99279798e-01 0.00000000e+00
 7.20201656e-04]
[0. 0. 1. 0. 0.]

1477
[0.99444444 0.         0.         0.         0.00555556]
[9.99461642e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[9.99279798e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[1. 0. 0. 0. 0.]

1478
[0.99444444 0.         0.         0.         0.00555556]
[9.99192463e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 8.07537012e-04]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

1479
[0.         0.99444444 0.         0.         0.00555556]
[0.00000000e+00 9.98923284e-01 2.69179004e-04 0.00000000e+00
 8.07537012e-04]
[0.00000000e+00 9.99459849e-01 0.000000

[1. 0. 0. 0. 0.]

1518
[0.         0.         0.99444444 0.         0.00555556]
[0.         0.         0.97227456 0.         0.02772544]
[0.        0.        0.9989197 0.        0.0010803]
[0. 0. 1. 0. 0.]

1519
[0.         0.         0.99444444 0.         0.00555556]
[0.         0.         0.97254374 0.         0.02745626]
[0.00000000e+00 0.00000000e+00 9.99099748e-01 0.00000000e+00
 9.00252071e-04]
[0. 0. 1. 0. 0.]

1520
[0.99444444 0.         0.         0.         0.00555556]
[0.97362046 0.         0.         0.         0.02637954]
[9.99099748e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.00252071e-04]
[1. 0. 0. 0. 0.]

1521
[0.         0.99444444 0.         0.         0.00555556]
[0.         0.97388964 0.         0.         0.02611036]
[0.00000000e+00 9.99099748e-01 0.00000000e+00 0.00000000e+00
 9.00252071e-04]
[0. 1. 0. 0. 0.]

1522
[0.99444444 0.         0.         0.         0.00555556]
[0.99057873 0.         0.         0.         0.00942127]
[9.99099748e-01 0.00000000e+0

[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99461642e-01
 5.38358008e-04]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99819950e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

1576
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99461642e-01
 5.38358008e-04]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99819950e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

1577
[1. 0. 0. 0. 0.]
[9.99461642e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.38358008e-04]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

1578
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99730821e-01 0.00000000e+00
 2.69179004e-04]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

1579
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99730821e-01 0.00000000e+00
 2.69179004e-04]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

1580
[0. 1. 0. 0. 0.]
[0.

[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

1816
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

1817
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 1.80050414e-03 9.98019445e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

1820
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

1821
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0.00298507 0.         0.         0.99701493 0.        ]

1826
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 1.80050414e-04 0.00000000e+00
 0.00000000e+00]
[0. 1. 0. 0. 0.]

1830
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 1.80050414e-04 9.99819950e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

1837
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.

 0.00000000e+00]
[1. 0. 0. 0. 0.]

1979
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99837955 0.00162045 0.         0.        ]
[0. 1. 0. 0. 0.]

1982
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

1986
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[1.80050414e-04 0.00000000e+00 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

1988
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 1.80050414e-04 9.99819950e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

1991
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

1992
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

1993
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

1994
[0. 0. 1. 0. 0.]
[0.         0.00215

[0.         0.         0.99701493 0.         0.00298507]

2053
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99730821e-01
 2.69179004e-04]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]

2054
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

2055
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

2056
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99730821e-01
 2.69179004e-04]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]

2057
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

2058
[0.00277778 0.         0.         0.99722222 0.        ]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99730821e-01
 2.69179004e-04]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

2059
[0. 1. 0. 0. 0.]
[0.000000

[1. 0. 0. 0. 0.]
[0.99701493 0.         0.         0.         0.00298507]

2112
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99701493 0.00298507]

2113
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

2114
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.         0.         0.00298507]

2115
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99730821e-01
 2.69179004e-04]
[0. 0. 0. 1. 0.]
[0.         0.         0.         0.99701493 0.00298507]

2116
[0.         0.00555556 0.99444444 0.         0.        ]
[0.00000000e+00 2.69179004e-04 9.99461642e-01 0.00000000e+00
 2.69179004e-04]
[0. 0. 1. 0. 0.]
[0.         0.         0.99701493 0.         0.00298507]

2117
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.0


2181
[0.         0.         0.99722222 0.         0.00277778]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]

2182
[0.         0.         0.99722222 0.         0.00277778]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.         0.00298507 0.99701493 0.         0.        ]

2183
[0.99722222 0.         0.         0.         0.00277778]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

2184
[0.         0.         0.         0.99722222 0.00277778]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]

2185
[0.         0.99722222 0.         0.         0.00277778]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

2186
[0.         0.         0.         0.99722222 0.00277778]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99730821e-01
 2.69179004e-04]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]

2187
[0.         0.99722222 0.         0.         0.00277778]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[0. 1. 0. 0. 

 1.80050414e-04]
[0. 0. 0. 1. 0.]

2294
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

2295
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99819950e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

2296
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

2304
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[1.80050414e-04 0.00000000e+00 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

2305
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

2332
[0.         0.00277778 0.99722222 0.         0.        ]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]

2333
[0.00277778 0.00277778 0.99444444 0.         0.        ]
[0. 0. 1. 0. 0.]
[3.60100828e-04 4.32120994e-03 9.95318689e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

2

[1. 0. 0. 0. 0.]

2427
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99459849e-01 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[0. 1. 0. 0. 0.]

2428
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99459849e-01 0.00000000e+00
 5.40151242e-04]
[0. 0. 1. 0. 0.]

2429
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.69179004e-04]
[9.99279798e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[1. 0. 0. 0. 0.]

2430
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

2431
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99459849e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.40151242e-04]
[1. 0. 0. 0. 0.]

2432
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99279798e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.20201656e-04]
[1. 0. 0. 0. 0.]

2433
[0. 0. 1. 0. 0.]
[0.00000000e+00 5.38358008e-04 9.99461642e-01 0.00000000e+00
 0.00000000e+00]
[0.00000000

[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

2506
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99639899e-01 0.00000000e+00 0.00000000e+00 1.80050414e-04
 1.80050414e-04]
[1. 0. 0. 0. 0.]

2507
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

2508
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

2509
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

2510
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

2511
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99819950e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

2512
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000

 1.80050414e-04]
[1. 0. 0. 0. 0.]

2703
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

2707
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 0.00000000e+00 9.99819950e-01 0.00000000e+00
 1.80050414e-04]
[0. 0. 1. 0. 0.]

2708
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

2709
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

2710
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

2711
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

2712
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

2713
[0. 0. 0. 1. 0.

2928
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99837955 0.00162045 0.         0.        ]
[0. 1. 0. 0. 0.]

2933
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99402985 0.00597015 0.         0.        ]

2943
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.        0.9981995 0.        0.0018005 0.       ]
[0. 1. 0. 0. 0.]

2954
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 3.60100828e-04 9.99639899e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

2972
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0.         0.00298507 0.         0.99701493 0.        ]

2990
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 5.40151242e-04 9.99459849e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

3008
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99701493 0.00298507 0.         0.        ]

3014
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.0

[0. 0. 0. 1. 0.]
[0.00000000e+00 5.40151242e-04 0.00000000e+00 9.99279798e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

3310
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

3311
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

3320
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[1.80050414e-04 0.00000000e+00 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

3324
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

3325
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

3326
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

3327
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000

[1. 0. 0. 0. 0.]

3486
[0.         0.00277778 0.         0.99722222 0.        ]
[0.         0.00188425 0.         0.99811575 0.        ]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

3488
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.         0.99747929 0.         0.00252071 0.        ]
[0. 1. 0. 0. 0.]

3490
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

3491
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[0. 1. 0. 0. 0.]

3492
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99819950e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

3493
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[9.99819950e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.80050414e-04]
[1. 0. 0. 0. 0.]

3494
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99819950e-01 0.00000000e+00 0.00000000e+00
 1.80050414e-

[0. 0. 0. 1. 0.]
[0.00000000e+00 3.60100828e-04 0.00000000e+00 9.99639899e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

3628
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99461642e-01 5.38358008e-04 0.00000000e+00
 0.00000000e+00]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]

3644
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 5.40151242e-04 9.99459849e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

3654
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 1.80050414e-04 0.00000000e+00 9.99819950e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

3655
[0.         0.00277778 0.         0.99722222 0.        ]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]

3656
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 0.00000000e+00 2.69179004e-04
 0.00000000e+00]
[0.00000000e+00 9.99819950e-01 1.80050414e-04 0.00000000e+00
 0.00000000e+00]
[0. 1. 0. 0. 0.]

3667
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.99819950e-01
 1.80050414e-04]
[0. 0. 0. 1. 0.]

3668
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.

 1.80050414e-04]
[0. 1. 0. 0. 0.]

3741
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0.        0.9985596 0.        0.0014404 0.       ]
[0. 1. 0. 0. 0.]

3745
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 1.80050414e-04 9.99819950e-01 0.00000000e+00
 0.00000000e+00]
[0. 0. 1. 0. 0.]

3748
[0. 0. 0. 1. 0.]
[0.00000000e+00 8.07537012e-04 0.00000000e+00 9.99192463e-01
 0.00000000e+00]
[0.        0.0010803 0.        0.9989197 0.       ]
[0. 0. 0. 1. 0.]

3750
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[5.40151242e-04 0.00000000e+00 0.00000000e+00 9.99459849e-01
 0.00000000e+00]
[0. 0. 0. 1. 0.]

3752
[1. 0. 0. 0. 0.]
[9.99730821e-01 0.00000000e+00 2.69179004e-04 0.00000000e+00
 0.00000000e+00]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]

3753
[0. 1. 0. 0. 0.]
[0.00000000e+00 9.99730821e-01 2.69179004e-04 0.00000000e+00
 0.00000000e+00]
[0.00000000e+00 9.99459849e-01 5.40151242e-04 0.00000000e+00
 0.00000000e+00]
[0. 1. 0. 0. 0.]

3755
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0.00000000e+00 1.80050414e-04 9.99819950e-01 